# mixed_timesheets.rules.toml

[META]
models=["account.analytic.line", "mrp.workcenter.production"]

# PRE-UNION
[account_analytic_line.FILTERING] # → pl.DataFrame.filter call
department_id="IS NOT NULL"
budget_type="IS NOT NULL"
[account_analytic_line.RENAMING.budget_type] # → pl.when().then().otherwise()
production="Production & Méthode"
# implied defaults
# _WHEN_NULL="_COL" # the value the column holds, untouched
# _OTHERWISE="_COL" # ditto
[account_analytic_line.RENAMING."employé"]
employee="Employé ALUVAL"
temporary="Intérimaire"
contractor="Sous Contrat/Sous-Traitants"
_WHEN_NULL="Non renseigné"
_OTHERWISE="Employé ALUVAL" # _ + majuscule : mot réservé

# POST-UNION
[union.PIVOT.months] 
# "MONTHS" is an arbitrary name. It must be different for each PIVOT operations
on="month"
index=["budget", "dept", "projet", "employé"]
values="heures"
aggregate_function="sum" # polars keywords must be used here

[union.COLUMN_RENAMING.months]
"12"='Décembre'
"1"="Janvier"
"2"='Février'
"3"='Mars'
"4"='Avril'
"5"='Mai'
"6"='Juin'

[union.GROUP_BY.final]
by=["budget", "dept", "employé"]
[union.GROUP_BY.final.AGG] # ignored if union.GROUP_BY.final.by doesn't exist
"Décembre"="sum"
Janvier="sum"
"Février"="sum"
Mars="sum"
Avril="sum"
Mai="sum"
Juin="sum"

[union.SORT.final]
by=["budget", "dept", "employé"]
_NULLS_LAST="true"

[union.NEW_COLUMN."Heures Totales"]
PL_OP="sum_horizontal" # pl.sum_horizontal(ON)
ON=["Décembre", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin"]
ADDITIONAL_OPS=["round"]

[union.SORT.other_final]
by=["budget", "Heures Totales"]
descending=["False", "True"]