{
    "name": "KpiTen",
    "summary": "Store kpiten KPI configuration",
    "version": "18.0.1.5.0",
    "development_status": "Alpha",
    "installable": True,
    "application": True,
    "category": "Tools",
    "website": "https://github.com/akretion/kpiten",
    "author": " Akretion",
    "license": "AGPL-3",
    "depends": [
        "base",
    ],
    "data": [
        "data/ir_config_parameter.xml",
        "data/misc.xml",
        "data/ir_cron.xml",
        "security/kpiten_security.xml",
        "security/ir.model.access.csv",
        "views/kpiten.xml",
        "views/kt_dataset.xml",
        "views/kt_panel.xml",
        "views/kt_config.xml",
    ],
}
