[STYLE]
[STYLE.header.style] # loc.header()
color="white"
fill="lightblue"

[STYLE.title.style] # loc.title()
color="white"
fill="lightblue"

[STYLE.body.style] # loc.body()
color="black" # style.text(color="", size=)
fill="lightblue" # style.fill(color="")
css="""
	/* custom CSS styles */*
"""

[STYLE.row_groups.style] # loc.row_group()
color="white"
fill="lightblue"

[OPTIONS] # .tab_options(...)
data_row_padding=2 # pixels