
services:
  kpiten:
    build: 
      context: .
    image: kpiten
    ports:
      - ${KPITEN_PORT}:5000

    networks: # everything here needs to match the bottom networks exactly. This is case sensitive.
      - sacpa_local
      - traefik

networks: # these should be changed to whatever network you need Kpiten to be in.
  sacpa_local:
    external: true
  traefik:
    external: true
