[project]
authors = [
  {name = "Maël Salem"},
  {name = "David Beal", email = "david.beal@akretion.com"},
]
dependencies = [
  "dotenv>=0.9.9",
  "fastapi>=0.135.3",
  "marimo>=0.24.0",
  "odoorpc>=0.10.1",
  "polars>=1.39.3",
  "pyarrow>=23.0.1",
  "requests>=2.33.1",
  "urllib3>=2.7.0",
  "uvicorn>=0.44.0",
  "werkzeug>=3.1.8",
  "plotly>=6.7.0",
  "numpy>=2.4.6",
  "great-tables>=0.21.0",
]
description = "Use marimo data exploration capabilities & dashboarding for Odoo"
name = "marimo-kpiten"
readme = "README.md"
requires-python = ">=3.12"
version = "0.6.0"

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.11.3,<0.12.0"]

[dependency-groups]
dev = [
  "black>=26.5.1",
]
