[project]
name = "marimo-kpiten"
version = "0.5.0"
description = "Use marimo data exploration capabilities & dashboarding"
readme = "README.md"
authors = [
    { name = "Maël Salem" },
    { name = "David Beal", email = "david.beal@akretion.com" },
]
requires-python = ">=3.12"
dependencies = [
    "altair>=6.1.0",
    "connectorx>=0.4.5",
    "dotenv>=0.9.9",
    "fastapi>=0.135.3",
    "marimo>=0.22.5",
    "odoorpc>=0.10.1",
    "pg-autojoin>=0.5.0",
    "polars>=1.39.3",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=23.0.1",
    "requests>=2.33.1",
    "urllib3>=2.7.0",
    "uvicorn>=0.44.0",
    "werkzeug>=3.1.8",
]

[project.scripts]
marimo-kpiten = "marimo_kpiten:main"

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
pg-autojoin = { git = "https://github.com/bealdav/pg-autojoin.git", rev = "main" }
